WITH raw_visit AS(
    SELECT *
    FROM {{ source('alaya_care', 'visit') }}
    WHERE _etl_is_deleted = FALSE
),
keep_required_columns AS(
    SELECT visit_id,
        guid,
        start_at,
        start_at_utc,
        end_at,
        end_at_utc,
        visit_completed,
        adl_complete,
        cancel_code_id,
        branch_id,
        visit_branch_timezone,
        service_id,
        service_code_id,
        visit_approval_status,
        visit_computed_rate_billitem_id,
        visit_scheduled_duration,
        idaccounttype,
        account_type,
        employee_id,
        client_id AS ac_client_id,
        service_instructions,
        visit_unit_qty,
        hours_bill,
        visit_hours_bill,
        break_minutes,
        break_hours,
        visit_pay,
        hours_pay,
        holiday_date,
        facility_id,
        client_visit_facility,
        visit_in_facility,
        visit_recurrence,
        visit_hours_approved,
        has_note,
        has_adl,
        visit_computed_rate,
        funder_validation_block_id,
        service_rrule_id,
        computed_rate_external_id,
        is_paid,
        visit_missed_class,
        visit_revenue,
        visit_on_hold_reason,
        visit_marked_for_resubmission,
        in_out_of_recurrence_status,
        recurrence_frequency_type,
        is_invoiced,
        visit_computed_rate_units,
        visit_note_count,
        modified_single,
        visit_billcode_id,
        visit_bill,
        visit_bill_duration,
        visit_revenue_breaktime,
        overwritten_client_cost_centre,
        latest_cancel_code_updated_at,
        latest_cancel_code_updated_by,
        latest_approval_status_updated_at,
        latest_approval_status_updated_by,
        created_at,
        created_by,
        updated_at,
        updated_by,
        _etl_is_deleted,
        _etl_updated_at_utc,
        __join_fields_hash
    FROM raw_visit
)
SELECT *
FROM keep_required_columns