echanalytics:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: snowflake
      authenticator: oauth
      oauth_client_id: "{{ env_var('DBT_OAUTH_CLIENT_ID') }}"
      oauth_client_secret: "{{ env_var('DBT_OAUTH_CLIENT_SECRET') }}"
      token: "{{ env_var('DBT_OAUTH_REFRESH_TOKEN') }}"
      account: "{{ env_var('DBT_DEV_SNOWFLAKE_ACCOUNT') }}"
      role: "{{ env_var('DBT_DEV_SNOWFLAKE_ROLE') }}"
      user: "{{ env_var('DBT_DEV_SNOWFLAKE_USER') }}"
      database: "{{ env_var('DBT_DEV_SNOWFLAKE_DB') }}"
      schema: "{{ env_var('DBT_DEV_SNOWFLAKE_SCHEMA') }}"
      warehouse: "{{ env_var('DBT_DEV_SNOWFLAKE_WH') }}"
      threads: 1

    prod:
      type: snowflake
      authenticator: oauth
      oauth_client_id: "{{ env_var('DBT_OAUTH_CLIENT_ID') }}"
      oauth_client_secret: "{{ env_var('DBT_OAUTH_CLIENT_SECRET') }}"
      token: "{{ env_var('DBT_OAUTH_REFRESH_TOKEN') }}"
      account: "{{ env_var('DBT_PROD_SNOWFLAKE_ACCOUNT') }}"
      role: "{{ env_var('DBT_PROD_SNOWFLAKE_ROLE') }}"
      user: "{{ env_var('DBT_PROD_SNOWFLAKE_USER') }}"
      database: "{{ env_var('DBT_PROD_SNOWFLAKE_DB') }}"
      schema: "{{ env_var('DBT_PROD_SNOWFLAKE_SCHEMA') }}"
      warehouse: "{{ env_var('DBT_PROD_SNOWFLAKE_WH') }}"
      threads: 1