WITH client AS (
    SELECT *
    FROM {{ ref('stg_ac_client') }}
),

client_tags AS (
    SELECT *
    FROM {{ ref('stg_ac_client_tags') }}
),

client_details AS (
    SELECT
        client.ac_client_id,
        client.profile_id,
        client.guid,
        client.alayacare_id,
        client.branch_id,
        client.mac_id,
        client.hcp_recipient_id,
        client.import_id,
        client.external_id,
        client.salutation,
        client.first_name,
        client.middle_name,
        client.last_name,
        client.preferred_name,
        client.birth_date,
        client.is_birth_date_an_estimate,
        client.gender,
        client.marital_status,
        client.client_status,
        client.religion,
        client.country_of_birth,
        client.language_spoken_at_home_code,
        client.email_comments,
        client.email,
        client.phone_comments,
        client.phone_main,
        client.phone_personal,
        client.phone_other,
        client.fax,
        client.pension_status,
        client.interpreter_required,
        client.address_suite,
        client.address,
        client.city,
        client.state,
        client.postcode,
        client.country,
        client.postal_address_line_1,
        client.postal_suburb,
        client.postal_state,
        client.postal_postcode,
        client.postal_country,
        client.mailing_address_1,
        client.mailing_address_2,
        client.mailing_suburb,
        client.mailing_state,
        client.mailing_post_code,
        client.mailing_country,
        client.billing_address_1,
        client.billing_address_2,
        client.billing_suburb,
        client.billing_state,
        client.billing_postcode,
        client.billing_country,
        client.ech_retirement_living_resident,
        client.hcp_approval_date,
        client.ambulance_card_number,
        client.carer_contact_name,
        client.account_contact_name,
        client.sms_contact_name,
        client.sms_contact_number,
        client.client_custom_stmt_delivery,
        client.deceased_date,
        client.time_of_death,
        client.death_location_category,
        client.disability_code,
        client.medicare_number,
        client.medicare_card_no,
        client.medicare_reference,
        client.medicare_card_expiry,
        client.ech_site_location_name,
        client.ech_assisted_living_resident,
        client.hcp_client_discharged_to_another_provider,
        client.client_ndis_number,
        client.is_first_nation,
        client.atsi_status,
        client.is_using_pseudonym,
        client.consent_to_record_lgbtiqa_status,
        client.consent_for_future_contacts,
        client.fastcard,
        client.dva_ref_prov_num,
        client.dva_card_number,
        client.dva_card_type,
        client.dva_ref_date,
        client.dva_entry_date,
        client.centrelink_reference_number,
        client.private_health_insurance,
        client.is_billing_contact,
        client.accommodation_type,
        client.d_365_debtor_id,
        client.living_arrangements,
        client.is_a_carer,
        client.education_level,
        client.ace,
        client.executor_contact_name,
        client.tags_v_2,
        client.consent_to_share_information,
        client.hcp_client_transfer_from_another_provider,
        client.has_carer,
        client.carer_residency,
        client.remarks,
        client.client_is_tpi,
        client_tags.tag_list
    FROM client
    LEFT JOIN client_tags
        ON client.ac_client_id = client_tags.ac_client_id
)

SELECT *
FROM client_details
