name: dbt Snowflake CD & Docs
on:
  # Trigger when code is merged or pushed directly to main branch
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  dbt-deploy-slim:
    runs-on: ubuntu-latest
    environment: production
    env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        SNOWFLAKE_DB: ${{ secrets.SNOWFLAKE_DB }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        SNOWFLAKE_WH: ${{ secrets.SNOWFLAKE_WH }}
        SNOWFLAKE_CLIENT_ID: ${{ secrets.SNOWFLAKE_CLIENT_ID }}
        SNOWFLAKE_CLIENT_SECRET: ${{ secrets.SNOWFLAKE_CLIENT_SECRET }}
        SNOWFLAKE_REFRESH_TOKEN: ${{ secrets.SNOWFLAKE_REFRESH_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'
        
      - name: Install dbt Adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.10.15 dbt-snowflake==1.10.3

      - name: Install dbt packages
        run: dbt deps

      # CD: Deploy directly to Production
      - name: Download Previous Manifest
        # Fetches manifest from the last successful CD run for state comparison
        uses: actions/download-artifact@v4
        with:
          branch: main
          name: dbt-manifest
          path: ./state
          if_no_artifact_found: warn
        continue-on-error: true

      - name: dbt Build (Production)
        # run: dbt build --target prod
        run: |
          if [ -f "./state/manifest.json" ]; then
            dbt build --target prod --select state:modified+ --state ./state
          else
            dbt build --target prod # Fallback to full build if no manifest exists
          fi

      - name: Upload Manifest for Next CD Run
        # This keeps your state persistent for the next 'state:modified' run
        uses: actions/upload-artifact@v4
        with:
          name: dbt-manifest
          path: target/manifest.json
        
      # Docs: Generate and Deploy to GitHub Pages
      - name: Generate Docs
        run: |
          dbt docs generate --target prod --static
          mkdir -p public
          cp target/static_index.html public/index.html

      - name: Upload Docs Artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
