name: dbt Snowflake Dev CI
on:
  # Trigger when a PR is created or updated the target dev branch
  pull_request:
    branches: [dev]
    types: [opened, synchronize, reopened]
  workflow_dispatch: # Allow manual trigger if required
  
  # Trigger when code is merged or pushed directly to dev branch
  push:
    branches: [dev]

jobs:
  dbt-dev-ci:
    runs-on: ubuntu-latest
    environment: development
    env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        SNOWFLAKE_DB: ${{ secrets.SNOWFLAKE_DB }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        SNOWFLAKE_WH: ${{ secrets.SNOWFLAKE_WH }}
        SNOWFLAKE_CLIENT_ID: ${{ secrets.SNOWFLAKE_CLIENT_ID }}
        SNOWFLAKE_CLIENT_SECRET: ${{ secrets.SNOWFLAKE_CLIENT_SECRET }}
        SNOWFLAKE_REFRESH_TOKEN: ${{ secrets.SNOWFLAKE_REFRESH_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dbt Adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.10.15 dbt-snowflake==1.10.3

      - name: Install dbt packages
        run: dbt deps

      - name: Run dbt debug (Verify Connection)
        run: dbt debug

      - name: Run dbt compile
        run: dbt compile --profiles-dir .

      - name: Download Previous Manifest
        # Fetches manifest from the last successful CI run for state comparison
        uses: actions/download-artifact@v4
        with:
          branch: dev
          name: dbt-manifest
          run-id: ${{ github.event.workflow_run.id }}
          path: ./state
          if_no_artifact_found: warn
        continue-on-error: true

      - name: dbt Build (Development)
        # run: dbt build --target prod
        run: |
          if [ -f "./state/manifest.json" ]; then
            dbt build --target dev --select state:modified+ --state ./state
          else
            dbt build --target dev # Fallback to full build if no manifest exists
          fi
      
      - name: Upload Manifest for Next Dev CI Run
        # This keeps your state persistent for the next 'state:modified' run
        uses: actions/upload-artifact@v4
        with:
          name: dbt-manifest
          path: target/manifest.json