name: dbt Snowflake CI
on:
  pull_request:
    branches:
      - [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.DEV_SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.DEV_SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.DEV_SNOWFLAKE_ROLE }}
          SNOWFLAKE_DB: ${{ secrets.DEV_SNOWFLAKE_DB }}
          SNOWFLAKE_SCHEMA: ${{ secrets.DEV_SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WH: ${{ secrets.DEV_SNOWFLAKE_WH }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install dbt-snowflake
      - name: Run dbt compile
        run: dbt compile --profiles-dir .
      - name: Run dbt tests in dev
        run: |
          dbt run --target dev
          dbt test --target dev